services:
  # Dịch vụ web Node.js
  - type: web
    name: ai-image-generation-app
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase: 
          name: ai-image-generation-db  # Tên cơ sở dữ liệu MySQL trên Render
          property: connectionString    # Thuộc tính connectionString để kết nối cơ sở dữ liệu
