services:
  - type: web
    name: ai-image-generation-app
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ai-image-generation-db
